apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanviapp-deployment
  namespace: default
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      app: test1
  replicas: 2
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
        - name: tanviapp
          image: nginx